server:
  port: 8090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/usuario?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: '#EeLcDmS2022*'

  jpa:
    hibernate:
      ddl-auto: update

  